### ISSUE TITLE
Delve failing to launch process from inside a Docker container

### ISSUE THREAD

**Issue by sssilver** [derekparker/delve#1109]
1. What version of Delve are you using (`dlv version`)?
1.0.0-rc2

2. What version of Go are you using? (`go version`)?
1.9.3 darwin/amd64

3. What operating system and processor architecture are you using?
macOS 10.13.3, 64-bit

4. What did you do?
I have a docker-compose multi-container application with the following entry point:
```
    test-hello:
        entrypoint:
            - dlv
            - exec
            - /opt/test/bin/test-hello
            - --
            - hello
            - first
        security_opt:
            - seccomp:unconfined
    ... # other services configured identically
```

When I launch the system, I get:
```
test-hello_1             | Could not create config directory: mkdir /nonexistent: permission denied.could not launch process: fork/exec /opt/test/bin/test-hello: exec format error
...same error for other services
```

The project is compiled with:
```
GOOS=linux GOARCH=amd64 /Library/Developer/CommandLineTools/usr/bin/make
go install -v -ldflags='-X "main.Version=2018.1.0-17-gd277e5f-dev" -X "main.BuildTime=2018-01-29-2023 UTC"' -gcflags "-N -l" -a code.example.com/test/test/cmd/test-hello
```

I leave the compiled binary on my host system and run it from the docker container through a mapped volume, to avoid rebuilding the docker image every time I change code (this is development mode). I can confirm that the binary is indeed built for Linux:
```
$ file bin/linux_amd64/test-hello
bin/linux_amd64/test-hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

5. What did you expect to see?
I expect the binary to properly be executed by Delve

6. What did you see instead?
Delve threw an error saying:
`Could not create config directory: mkdir /nonexistent: permission denied.could not launch process: fork/exec /opt/test/bin/test-hello: exec format error`

Please advise. Many thanks.

**Comment by dlsniper** [comment]
It looks like you are trying to debug a non-Linux executable ` exec format error `. Are you cross-compiling to a Linux target? Or do you build in the same container?

**Comment by sssilver** [comment]
I build on the host machine with the compiler flags to build a Linux binary:

```
GOOS=linux GOARCH=amd64 /Library/Developer/CommandLineTools/usr/bin/make
go install -v -ldflags='-X "main.Version=2018.1.0-17-gd277e5f-dev" -X "main.BuildTime=2018-01-29-2023 UTC"' -gcflags "-N -l" -a code.example.com/test/test/cmd/test-hello
```

I figure that the binary is a proper Linux binary, because:
```
$ file bin/linux_amd64/test-hello
bin/linux_amd64/test-hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

**Comment by dlsniper** [comment]
Sorry, I've missed that in the original report.

You also need to add ` --security-opt="apparmor=unconfined" --cap-add=SYS_PTRACE ` when you use ` docker run ` for the container. You can have a look at this for how to run it: https://github.com/dlsniper/webinar/blob/master/container-debug.sh#L10-L11

Also, make sure that your container, if it's based on Alpine, has ` libc6-compat ` installed, otherwise delve won't work.

**Comment by sssilver** [comment]
I'm getting a bit desperate here. New docker-compose:
```
    test-hello:
        entrypoint:
            - dlv
            - exec
            - /opt/test/bin/test-hello
            - --
            - hello
            - first
        security_opt:
            - seccomp:unconfined
            - apparmor=unconfined
            - apparmor:unconfined  # Yes I'm trying everything here
        cap_add:
            - SYS_PTRACE
    ...
```

I've also removed `USER nobody` from my Dockerfile which solved the "Could not create config directory" error, although I suppose it would be nice if Delve supported externally passing the config directory or working without having to create a default config on the filysystem.

However, even with the new docker-compose config, I still have the same error:
```
could not launch process: fork/exec /opt/test/bin/test-hello: exec format error
```

My container is based on Debian/jessie, so libc6-compat shouldn't be an issue.

I can confirm that when I'm building a binary for macOS and attaching to it on my local machine, it works. I can also confirm, that when I'm trying to run the exact same Linux binary in the container without Delve, it works as well.

All input is appreciated -- I have been banging my head against this wall for quite a bit now.
